<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

namespace com\example\authors\postgresql;

class Authors {
  public function __construct(
  public int $id,
  public string $name,
  public ?string $bio,
    )
    {
    }
}

