<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\CountExchanges;

final readonly class Exchange {
    public function __construct(
        public int $id,
        public string $name,
    )
    {}
}

