<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\CountExchanges;

interface Queries {
  public function countExchanges(): ?int;
  
  /**
  *  @return GetAllExchangesRow[]
  */
  public function getAllExchanges(): array;
  
  public function getIdByName(string $name): ?int;
  
}

