<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\Basic;

interface Queries {
  public function getAuthor(int $authorId): ?Author;
  
  /**
  *  @return array<Author>
  */
  public function listAuthors(): array;
  
}

