<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

namespace com\example\authors\mysql;

class Author {
  private int $id;
  private string $name;
  private ?string $bio;
}

