<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\ArgsWithDefaults;

interface Queries {
  public function insertAuthor(int $id, int $age, string $name): void;
  
}

