<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\ArgsWithDefaults;

const insertAuthor = "-- name: insertAuthor :exec
INSERT INTO
    author (id, name, age)
VALUES
    (?1, ?2, ?3)
";

final readonly class QueriesImpl implements Queries {
    public function __construct(private \PDO $pdo) {}

    /**
     * @sqlc-param int $id
     * @sqlc-param string $name='hello'
     * @sqlc-param int $age
     * @throws \Exception
     */
    public function insertAuthor(int $id, int $age, string $name = 'hello'): void
    {
        $stmt = $this->pdo->prepare(insertAuthor);
        $stmt->execute([$id, $name, $age]);
    }

}

