<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\BooleanBindings;

interface Queries {
  /**
  *  @return FeatureFlags[]
  */
  public function listFlags(): array;
  
  public function setFlag(int $id, string $name, bool $enabled): void;
  
}

