<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\BooleanBindings;

const listFlags = "-- name: listFlags :many
SELECT
    id,
    name,
    enabled
FROM
    feature_flags
ORDER BY
    id
";

const setFlag = "-- name: setFlag :exec
INSERT INTO
    feature_flags (id, name, enabled)
VALUES
    (?, ?, ?)
";

final readonly class QueriesImpl implements Queries {
    public function __construct(private \PDO $pdo) {}

    /**
     * @return FeatureFlags[]
     * @throws \Exception
     */
    public function listFlags(): array
    {
        $stmt = $this->pdo->prepare(listFlags);
        $stmt->execute();
        $results = $stmt->fetchAll(\PDO::FETCH_NUM);
        $ret = [];
        foreach ($results as $row) {
            $ret[] = new FeatureFlags($row[0], $row[1], $row[2]);
        }
        return $ret;
    }

    /**
     * @throws \Exception
     */
    public function setFlag(int $id, string $name, bool $enabled): void
    {
        $stmt = $this->pdo->prepare(setFlag);
        $stmt->execute([$id, $name, ($enabled ? 1 : 0)]);
    }

}

