<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\BoolType;

final readonly class Dummy {
    public function __construct(
        public bool $flag,
    )
    {}
}

