<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\BoolType;

const getFlag = "-- name: getFlag :one
SELECT
    flag
from
    dummy
LIMIT
    1
";

final readonly class QueriesImpl implements Queries {
    public function __construct(private \PDO $pdo) {}

    /**
     * @return bool|null
     * @throws \Exception
     */
    public function getFlag(): ?bool
    {
        $stmt = $this->pdo->prepare(getFlag);
        $stmt->execute();
        $results = $stmt->fetchAll(\PDO::FETCH_COLUMN);
        $ret = [];
        if(count($results) != 1){
            throw new \Exception('Expected exactly 1 row, but got ' . count($results));
        }

        $row = $results[0];
        $ret[] = (bool)($row);
        return $ret[0];
    }

}

