<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

declare(strict_types=1);

namespace App\Sqlc\MySQL;

final readonly class Book {
    public function __construct(
        public int $bookId,
        public int $authorId,
        public string $isbn,
        public string $bookType,
        // UUID
        public string $title,
        public int $yr,
        public \DateTimeImmutable $available,
        public string $tags,
    )
    {}
}

