<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

declare(strict_types=1);

namespace App\Sqlc\MySQL;

interface Queries {
  /**
  *  @return array<BookByTagsRow>
  */
  public function bookByTags(string $tags): array;
  
  /**
  *  @return array<BookByTagsMultipleRow>
  */
  public function bookByTagsMultiple(array $tags): array;
  
  /**
  *  @return array<Book>
  */
  public function bookByTitleYear(string $uuidToBin, int $yr): array;
  
  public function createAuthor(string $name): int;
  
  public function createBook(
      int $authorId,
      string $isbn,
      string $bookType,
      string $uuidToBin,
      int $yr,
      \DateTimeImmutable $available,
      string $tags): int;
  
  public function deleteAuthorBeforeYear(int $yr, int $authorId): void;
  
  public function deleteBook(int $bookId): void;
  
  public function getAuthor(int $authorId): ?Author;
  
  public function getBook(int $bookId): ?Book;
  
  public function updateBook(
      string $title,
      string $tags,
      int $bookId): void;
  
  public function updateBookISBN(
      string $title,
      string $tags,
      string $isbn,
      int $bookId): void;
  
}

