<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

namespace App\Sqlc\MySQL;

class Author {
  public function __construct(
  public int $authorId,
  public string $name,
    )
    {
    }
}

class Book {
  public function __construct(
  public int $bookId,
  public int $authorId,
  public string $isbn,
  public string $bookType,
  // UUID
  public string $title,
  public int $yr,
  public \DateTimeImmutable $available,
  public string $tags,
    )
    {
    }
}

