<?php
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

declare(strict_types=1);

namespace App\Sqlc\MySQL;

final readonly class BookByTagsRow {
    public function __construct(
        public int $bookId,
        public string $title,
        public ?string $name,
        public string $isbn,
        public string $tags,
    )
    {}
}

