<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace App\Sqlc\SQLite;

final readonly class Book {
    public function __construct(
        public int $bookId,
        public int $authorId,
        public string $isbn,
        public string $bookType,
        public string $title,
        public int $yr,
        public string $available,
        public string $tags,
    )
    {}
}

