<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace App\Sqlc\SQLite;

interface Queries {
  /**
  *  @return BookByTagsRow[]
  */
  public function bookByTags(string $tags): array;
  
  /**
  *  @return BookByTagsMultipleRow[]
  */
  public function bookByTagsMultiple(array $tags): array;
  
  /**
  *  @return Book[]
  */
  public function bookByTitleYear(mixed $uuidToBin, int $yr): array;
  
  public function createAuthor(string $name): int|string;
  
  public function createBook(int $authorId, string $isbn, string $bookType, mixed $uuidToBin, int $yr, string $available, string $tags): int|string;
  
  public function deleteAuthorBeforeYear(int $yr, int $authorId): void;
  
  public function deleteBook(int $bookId): void;
  
  public function getAuthor(int $authorId): ?Author;
  
  public function getBook(int $bookId): ?Book;
  
  /**
  *  @return Author[]
  */
  public function listAuthors(): array;
  
  public function updateBook(string $title, string $tags, int $bookId): void;
  
  public function updateBookISBN(string $title, string $tags, string $isbn, int $bookId): void;
  
}

