<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\JSON;

interface Queries {
  public function createAuthor(array $data): void;
  
  public function getAuthor(int $authorId): ?Author;
  
  /**
  *  @return Author[]
  */
  public function listAuthors(): array;
  
}

