<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\DateTimeImmutable;

final readonly class Author {
    public function __construct(
        public int $id,
        public string $name,
        public string $createdAt,
    )
    {}
}

