<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\DateTimeImmutable;

interface Queries {
  public function addAuthor(string $name, ?\DateTimeImmutable $createdAt): void;
  
  public function getAuthorByCreatedAt(\DateTimeImmutable $createdAt): ?Author;
  
}

