<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\DateTimeImmutable;

interface Queries {
  public function addAuthor(string $name, ?string $createdAt): void;
  
  public function getAuthorByCreatedAt(string $createdAt): ?Author;
  
}

