<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\ExtraComments;

final readonly class Entity {
    public function __construct(
        public string $id,
        public string $title,
        public array $data,
        public int $locked,
        public string $lockedMessage,
        public ?string $ownerId,
        public string $createdAt,
        public string $updatedAt,
    )
    {}
}

