<?php
// @formatter:off
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

declare(strict_types=1);

namespace Test\ExtraComments;

interface Queries {
  /**
  *  @return Entity[]
  */
  public function listEntities(
      mixed $locked,
      mixed $ownerId,
      mixed $title): array;
  
}

