name: Release sqlc-gen-php.wasm

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.23"

      - name: Build wasm binary
        run: make bin/sqlc-gen-php.wasm

      - name: Generate checksum
        run: |
          sha256sum bin/sqlc-gen-php.wasm > bin/sqlc-gen-php.wasm.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/sqlc-gen-php.wasm
            bin/sqlc-gen-php.wasm.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
